#!/usr/bin/env bash
# Install nginx server.

sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo chmod 644 /var/www/html/index.nginx-debian.html
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
service nginx restart
