#!/usr/bin/env bash
# configure a new nginx server.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
newline="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $newline" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
