#!/usr/bin/env bash
# Configure a server with haproxy

sudo apt-get -y update
sudo apt-get install -y nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx start

