#!/usr/bin/env bash
#A bash script


echo $$ > /var/run/holbertonscript.pid

while :
do
trap "rm /var/run/holbertonscript.pid"  SIGTERM
trap "echo 'I hate the kill command'" SIGTERM

trap "echo 'Y U no love me?!'" SIGINT
trap  "rm /var/run/holbertonscript.pid" SIGQUIT
echo 'To infinity and beyond'

done
