#!/usr/bin/env bash
#displays minutes for 12 hour loop

hour=0

while [ $hour -lt 13 ]; do
min=1
    echo "Hour: $hour"
    while [ $min -lt 60 ]; do
 echo "$min"
        ((min++))
    done
    	((hour++))
done
