#!/usr/bin/env bash
#change the ip adress for the facebook and local
cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
echo "8.8.8.8 facebook.com" >> hosts_new
cp hosts_new /etc/hosts
